"""
Definiciones de workbenches (superficies de trabajo en sidebar).
"""
from __future__ import annotations

from typing import Any

from app.domain.capabilities import (
    WORKBENCH_ACTIVITY,
    WORKBENCH_FEATURES,
    WORKBENCH_HUB,
    WORKBENCH_INBOX_CLIENT,
    WORKBENCH_INBOX_DEV,
    WORKBENCH_INBOX_PM,
    WORKBENCH_INBOX_QA,
    WORKBENCH_KANBAN,
    WORKBENCH_MY_DELIVERIES,
    WORKBENCH_MY_TASKS,
    WORKBENCH_OVERVIEW,
    WORKBENCH_SCOPE,
    WORKBENCH_SETTINGS,
    WORKBENCH_TIMELINE,
    WORKBENCH_UAT,
)

DEFAULT_WORKBENCHES: list[dict[str, Any]] = [
    {
        "key": "overview",
        "label": "Resumen",
        "route": "overview",
        "icon": "layout-dashboard",
        "section": "pm",
        "required_capabilities": [WORKBENCH_OVERVIEW],
        "orden": 10,
    },
    {
        "key": "inbox_pm",
        "label": "Bandeja",
        "route": "inbox",
        "icon": "inbox",
        "section": "pm",
        "required_capabilities": [WORKBENCH_INBOX_PM],
        "queue_filter": {"entity_types": ["report", "query", "feature"], "state_categories": ["inbox_pm"]},
        "orden": 20,
    },
    {
        "key": "inbox_dev",
        "label": "Bandeja",
        "route": "dev/inbox",
        "icon": "inbox",
        "section": "dev",
        "required_capabilities": [WORKBENCH_INBOX_DEV],
        "orden": 30,
    },
    {
        "key": "kanban",
        "label": "Kanban",
        "route": "kanban",
        "icon": "columns-3",
        "section": "dev",
        "required_capabilities": [WORKBENCH_KANBAN],
        "orden": 40,
    },
    {
        "key": "my_tasks",
        "label": "Mis tareas",
        "route": "dev/my-tasks",
        "icon": "list-checks",
        "section": "dev",
        "required_capabilities": [WORKBENCH_MY_TASKS],
        "orden": 50,
    },
    {
        "key": "my_deliveries",
        "label": "Mis entregas",
        "route": "dev/features",
        "icon": "package",
        "section": "dev",
        "required_capabilities": [WORKBENCH_MY_DELIVERIES],
        "orden": 60,
    },
    {
        "key": "inbox_qa",
        "label": "Bandeja",
        "route": "qa/inbox",
        "icon": "inbox",
        "section": "qa",
        "required_capabilities": [WORKBENCH_INBOX_QA],
        "orden": 70,
    },
    {
        "key": "uat",
        "label": "Validación UAT",
        "route": "qa",
        "icon": "shield-check",
        "section": "qa",
        "required_capabilities": [WORKBENCH_UAT],
        "queue_filter": {"entity_types": ["feature"], "state_categories": ["uat"]},
        "orden": 80,
    },
    {
        "key": "inbox_client",
        "label": "Bandeja",
        "route": "client/inbox",
        "icon": "inbox",
        "section": "client",
        "required_capabilities": [WORKBENCH_INBOX_CLIENT],
        "orden": 90,
    },
    {
        "key": "scope",
        "label": "Alcance",
        "route": "scope",
        "icon": "target",
        "section": "plan",
        "required_capabilities": [WORKBENCH_SCOPE],
        "orden": 100,
    },
    {
        "key": "features",
        "label": "Features",
        "route": "features",
        "icon": "layers",
        "section": "plan",
        "required_capabilities": [WORKBENCH_FEATURES],
        "orden": 110,
    },
    {
        "key": "hub",
        "label": "Centro del proyecto",
        "route": "hub",
        "icon": "book-open",
        "section": "plan",
        "required_capabilities": [WORKBENCH_HUB],
        "orden": 120,
    },
    {
        "key": "timeline",
        "label": "Cronograma",
        "route": "timeline",
        "icon": "calendar-range",
        "section": "plan",
        "required_capabilities": [WORKBENCH_TIMELINE],
        "orden": 130,
    },
    {
        "key": "activity",
        "label": "Actividad",
        "route": "activity",
        "icon": "activity",
        "section": "track",
        "required_capabilities": [WORKBENCH_ACTIVITY],
        "orden": 140,
    },
    {
        "key": "settings",
        "label": "Configuración",
        "route": "settings",
        "icon": "settings",
        "section": "admin",
        "required_capabilities": [WORKBENCH_SETTINGS],
        "orden": 150,
    },
]

SECTION_LABELS: dict[str, str] = {
    "pm": "PM",
    "dev": "Desarrollo",
    "qa": "Calidad",
    "client": "Cliente",
    "plan": "Planificación",
    "track": "Seguimiento",
    "admin": "Administración",
}
